id: 0bd6f70e99014aaab3905f98d3d761b5
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_1-1-The_Chapter_on_Going_Forth-v1
  language: en
  author: ''
  volume: {}
